//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.24 at 08:44:37 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.dorozhko.by/tariffs", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.dorozhko.xmlparse.tariffs;
