//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.24 at 08:44:37 PM MSK 
//


package by.dorozhko.xmlparse.tariffs;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VoiceTariff complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VoiceTariff">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.dorozhko.by/tariffs}TariffType">
 *       &lt;sequence>
 *         &lt;element name="call_price">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="in_operator">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *                         &lt;minInclusive value="0"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="other_operators">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *                         &lt;minInclusive value="0"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="sms_price">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="parametrs">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="tarification">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="per second"/>
 *                         &lt;enumeration value="per minute"/>
 *                         &lt;enumeration value="per 12 second"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="connectiong" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="date">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="launch_date" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;pattern value="(([0-2][0-9])||([3][0-1]))-(([0][1-9])||([1][0-2]))-[0-9]{4}"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="archive_date">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;pattern value="(([0-2][0-9])||([3][0-1]))-(([0][1-9])||([1][0-2]))-[0-9]{4}"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VoiceTariff", propOrder = {
    "callPrice",
    "smsPrice",
    "parametrs",
    "date"
})
public class VoiceTariff
    extends TariffType
{

    @XmlElement(name = "call_price", required = true)
    protected VoiceTariff.CallPrice callPrice = new VoiceTariff.CallPrice();
    @XmlElement(name = "sms_price")
    protected double smsPrice;
    @XmlElement(required = true)
    protected VoiceTariff.Parametrs parametrs = new VoiceTariff.Parametrs();
    @XmlElement(required = true)
    protected VoiceTariff.Date date = new VoiceTariff.Date();

    /**
     * Gets the value of the callPrice property.
     * 
     * @return
     *     possible object is
     *     {@link VoiceTariff.CallPrice }
     *     
     */
    public VoiceTariff.CallPrice getCallPrice() {
        return callPrice;
    }

    /**
     * Sets the value of the callPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link VoiceTariff.CallPrice }
     *     
     */
    public void setCallPrice(VoiceTariff.CallPrice value) {
        this.callPrice = value;
    }

    /**
     * Gets the value of the smsPrice property.
     * 
     */
    public double getSmsPrice() {
        return smsPrice;
    }

    /**
     * Sets the value of the smsPrice property.
     * 
     */
    public void setSmsPrice(double value) {
        this.smsPrice = value;
    }

    /**
     * Gets the value of the parametrs property.
     * 
     * @return
     *     possible object is
     *     {@link VoiceTariff.Parametrs }
     *     
     */
    public VoiceTariff.Parametrs getParametrs() {
        return parametrs;
    }

    /**
     * Sets the value of the parametrs property.
     * 
     * @param value
     *     allowed object is
     *     {@link VoiceTariff.Parametrs }
     *     
     */
    public void setParametrs(VoiceTariff.Parametrs value) {
        this.parametrs = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link VoiceTariff.Date }
     *     
     */
    public VoiceTariff.Date getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link VoiceTariff.Date }
     *     
     */
    public void setDate(VoiceTariff.Date value) {
        this.date = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="in_operator">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
     *               &lt;minInclusive value="0"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="other_operators">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
     *               &lt;minInclusive value="0"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "inOperator",
        "otherOperators"
    })
    public static class CallPrice {
        @Override
        public String toString() {
            return "CallPrice{" +
                    "inOperator=" + inOperator +
                    ", otherOperators=" + otherOperators +
                    '}';
        }

        @XmlElement(name = "in_operator", defaultValue = "0")
        protected double inOperator;
        @XmlElement(name = "other_operators")
        protected double otherOperators;

        /**
         * Gets the value of the inOperator property.
         * 
         */
        public double getInOperator() {
            return inOperator;
        }

        /**
         * Sets the value of the inOperator property.
         * 
         */
        public void setInOperator(double value) {
            this.inOperator = value;
        }

        /**
         * Gets the value of the otherOperators property.
         * 
         */
        public double getOtherOperators() {
            return otherOperators;
        }

        /**
         * Sets the value of the otherOperators property.
         * 
         */
        public void setOtherOperators(double value) {
            this.otherOperators = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="launch_date" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;pattern value="(([0-2][0-9])||([3][0-1]))-(([0][1-9])||([1][0-2]))-[0-9]{4}"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="archive_date">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;pattern value="(([0-2][0-9])||([3][0-1]))-(([0][1-9])||([1][0-2]))-[0-9]{4}"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Date {

        @XmlAttribute(name = "launch_date", required = true)
        protected String launchDate;
        @XmlAttribute(name = "archive_date")
        protected String archiveDate;

        /**
         * Gets the value of the launchDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLaunchDate() {
            return launchDate;
        }

        /**
         * Sets the value of the launchDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLaunchDate(String value) {
            this.launchDate = value;
        }

        /**
         * Gets the value of the archiveDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getArchiveDate() {
            return archiveDate;
        }

        /**
         * Sets the value of the archiveDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setArchiveDate(String value) {
            this.archiveDate = value;
        }

        @Override
        public String toString() {
            return "Date{" +
                    "launchDate='" + launchDate + '\'' +
                    ", archiveDate='" + archiveDate + '\'' +
                    '}';
        }
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="tarification">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="per second"/>
     *               &lt;enumeration value="per minute"/>
     *               &lt;enumeration value="per 12 second"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="connectiong" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tarification",
        "connectiong"
    })
    public static class Parametrs {

        @XmlElement(required = true)
        protected String tarification;
        @XmlElement(required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected Integer connectiong;

        /**
         * Gets the value of the tarification property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTarification() {
            return tarification;
        }

        /**
         * Sets the value of the tarification property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTarification(String value) {
            this.tarification = value;
        }

        @Override
        public String toString() {
            return "Parametrs{" +
                    "tarification='" + tarification + '\'' +
                    ", connectiong=" + connectiong +
                    '}';
        }

        /**
         * Gets the value of the connectiong property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public int getConnectiong() {
            return connectiong;
        }

        /**
         * Sets the value of the connectiong property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setConnectiong(Integer value) {
            this.connectiong = value;
        }

    }

    @Override
    public String toString() {
        return "VoiceTariff{" +
                "callPrice=" + callPrice +
                ", smsPrice=" + smsPrice +
                ", parametrs=" + parametrs +
                ", date=" + date +
                ", name='" + name + '\'' +
                ", operatorName='" + operatorName + '\'' +
                ", payroll=" + payroll +
                '}';
    }
}
